### ISSUE TITLE
GithubException: 422 {"message": "refs/tags/ is not a valid ref name

### ISSUE THREAD

**Issue by minerop5000** [Amraneze/push-to-protected-branch#3]
action setup:
```
      - name: Commit and push
        uses: Amraneze/push-to-protected-branch@v1.5.0
        with:
          repository: ${{ github.repository }}
          branch_name: main
          github_token: ${{ secrets.PAT_CLASSIC_REPO }}
          commit_message: "bump version ${{ steps.gitversion.outputs.majorMinorPatch }}"
          files_to_commit: "pubspec.yaml"
```

is running as:
```
Run Amraneze/push-to-protected-branch@v1.5.0
  with:
    repository: budgetiser/budgetiser
    branch_name: main
    github_token: ***
    commit_message: bump version 1.10.19
    files_to_commit: pubspec.yaml
    create_tag: false
```

I get this error message:
```
Traceback (most recent call last):
  File "/action/workspace/main.py", line 27, in <module>
    repository.create_git_ref(
  File "/usr/local/lib/python3.8/site-packages/github/Repository.py", line 970, in create_git_ref
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "refs/tags/ is not a valid ref name.", "documentation_url": "https://docs.github.com/rest/git/refs#create-a-reference"}
```

Help would be appreciated!

**Comment by kaidoki** [comment]
Hello. Have you managed to solve this issue? I have exactly the same error and can't find any useful hints.
